### ISSUE TITLE
Not working with Docker Swarm

### ISSUE THREAD

**Issue by vforv** [senecajs/seneca-mesh#94]
I think I tried all possible solutions but there is no chance to connect services to base.

I am using:
seneca mesh 0.10
digitalocean
Overlay docker swarm network

I am able to ping between containers...

Bases start normaly but when I try to connect service to it, service just crash...

I try also few more combination to add on bases host, port, bases params... I noticed when I added bases param service cannot start.

This is one of possible combinations I tried:

```
version: '3'

networks:
  trifacta:
    driver: overlay

services:
  bases:
    image: vforv/bases:v1
    networks:
      trifacta:
        aliases: 
          - bases
    environment:
      PORT: 39000
      HOST: bases
      BASES: bases:39000
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
      HOST: '@eth0'
      BASES: bases:39000
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v1
    networks:
        - trifacta
    environment:
      HOST: '@eth0'
      BASES: bases:39000
    command: bash -c "cd ping-service && npm start"
```

What can be a problem?
